-- Oracle Package 3018
CREATE OR REPLACE PACKAGE pkg_3018 AS
  FUNCTION calc_3018(p_base NUMBER, p_rate NUMBER, p_n INT) RETURN NUMBER;
END pkg_3018;
/
CREATE OR REPLACE PACKAGE BODY pkg_3018 AS
  FUNCTION calc_3018(p_base NUMBER, p_rate NUMBER, p_n INT) RETURN NUMBER IS
    v NUMBER:=p_base;
  BEGIN FOR i IN 1..p_n LOOP v:=v*(1+p_rate); END LOOP; RETURN v; END;
END pkg_3018;
/
