-- MSSQL Columnstore 3131
CREATE SCHEMA cs_3131;
GO
CREATE TABLE cs_3131.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_3131.summarize_3131 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_3131.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
