-- MSSQL Columnstore 2035
CREATE SCHEMA cs_2035;
GO
CREATE TABLE cs_2035.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_2035.summarize_2035 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_2035.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
