-- MSSQL Columnstore 4047
CREATE SCHEMA cs_4047;
GO
CREATE TABLE cs_4047.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_4047.summarize_4047 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_4047.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
