-- MSSQL Columnstore 1171
CREATE SCHEMA cs_1171;
GO
CREATE TABLE cs_1171.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_1171.summarize_1171 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_1171.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
