-- MSSQL Columnstore 7055
CREATE SCHEMA cs_7055;
GO
CREATE TABLE cs_7055.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_7055.summarize_7055 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_7055.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
