-- MSSQL Columnstore 4115
CREATE SCHEMA cs_4115;
GO
CREATE TABLE cs_4115.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_4115.summarize_4115 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_4115.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
