-- MSSQL Columnstore 1107
CREATE SCHEMA cs_1107;
GO
CREATE TABLE cs_1107.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_1107.summarize_1107 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_1107.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
