-- MSSQL Columnstore 6067
CREATE SCHEMA cs_6067;
GO
CREATE TABLE cs_6067.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_6067.summarize_6067 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_6067.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
