-- MSSQL Columnstore 5027
CREATE SCHEMA cs_5027;
GO
CREATE TABLE cs_5027.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_5027.summarize_5027 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_5027.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
