-- MSSQL Columnstore 7155
CREATE SCHEMA cs_7155;
GO
CREATE TABLE cs_7155.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_7155.summarize_7155 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_7155.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
