-- MSSQL Columnstore 6043
CREATE SCHEMA cs_6043;
GO
CREATE TABLE cs_6043.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_6043.summarize_6043 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_6043.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
