-- MSSQL Columnstore 3059
CREATE SCHEMA cs_3059;
GO
CREATE TABLE cs_3059.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_3059.summarize_3059 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_3059.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
