-- MSSQL Columnstore 7095
CREATE SCHEMA cs_7095;
GO
CREATE TABLE cs_7095.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_7095.summarize_7095 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_7095.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
