-- MSSQL Columnstore 4035
CREATE SCHEMA cs_4035;
GO
CREATE TABLE cs_4035.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_4035.summarize_4035 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_4035.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
