-- MSSQL Columnstore 5003
CREATE SCHEMA cs_5003;
GO
CREATE TABLE cs_5003.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_5003.summarize_5003 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_5003.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
