-- MSSQL Columnstore 4083
CREATE SCHEMA cs_4083;
GO
CREATE TABLE cs_4083.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_4083.summarize_4083 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_4083.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
