-- MSSQL Columnstore 1151
CREATE SCHEMA cs_1151;
GO
CREATE TABLE cs_1151.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_1151.summarize_1151 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_1151.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
