-- MSSQL Columnstore 7119
CREATE SCHEMA cs_7119;
GO
CREATE TABLE cs_7119.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_7119.summarize_7119 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_7119.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
