-- MSSQL Columnstore 2007
CREATE SCHEMA cs_2007;
GO
CREATE TABLE cs_2007.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_2007.summarize_2007 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_2007.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
