-- MSSQL Columnstore 7075
CREATE SCHEMA cs_7075;
GO
CREATE TABLE cs_7075.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_7075.summarize_7075 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_7075.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
