-- MSSQL Columnstore 6087
CREATE SCHEMA cs_6087;
GO
CREATE TABLE cs_6087.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_6087.summarize_6087 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_6087.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
