-- MSSQL Columnstore 3147
CREATE SCHEMA cs_3147;
GO
CREATE TABLE cs_3147.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_3147.summarize_3147 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_3147.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
