-- MSSQL Columnstore 1143
CREATE SCHEMA cs_1143;
GO
CREATE TABLE cs_1143.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_1143.summarize_1143 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_1143.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
