-- MSSQL Columnstore 6127
CREATE SCHEMA cs_6127;
GO
CREATE TABLE cs_6127.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_6127.summarize_6127 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_6127.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
