-- MSSQL Columnstore 3159
CREATE SCHEMA cs_3159;
GO
CREATE TABLE cs_3159.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_3159.summarize_3159 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_3159.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
