-- MSSQL Columnstore 3007
CREATE SCHEMA cs_3007;
GO
CREATE TABLE cs_3007.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_3007.summarize_3007 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_3007.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
