-- MSSQL Columnstore 2119
CREATE SCHEMA cs_2119;
GO
CREATE TABLE cs_2119.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_2119.summarize_2119 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_2119.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
