-- MSSQL Columnstore 4131
CREATE SCHEMA cs_4131;
GO
CREATE TABLE cs_4131.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_4131.summarize_4131 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_4131.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
