-- MSSQL Columnstore 5011
CREATE SCHEMA cs_5011;
GO
CREATE TABLE cs_5011.signals (
  id BIGINT IDENTITY(1,1), uid UNIQUEIDENTIFIER DEFAULT NEWID(),
  val FLOAT NOT NULL, ts DATETIME2(7) DEFAULT SYSUTCDATETIME(),
  INDEX cci CLUSTERED COLUMNSTORE
);
GO
CREATE PROCEDURE cs_5011.summarize_5011 AS BEGIN SET NOCOUNT ON;
  SELECT DATETRUNC(hour,ts) h, AVG(val) avg_val, COUNT(*) cnt
  FROM cs_5011.signals GROUP BY DATETRUNC(hour,ts);
END;
GO
