-- MySQL Partitioned Store 4069
CREATE DATABASE IF NOT EXISTS telemetry_4069;
USE telemetry_4069;
CREATE TABLE IF NOT EXISTS events_4069 (
  id BIGINT NOT NULL AUTO_INCREMENT, device_id INT NOT NULL,
  val INT NOT NULL, ts DATETIME NOT NULL,
  PRIMARY KEY(id,ts), INDEX idx_4069(device_id,ts)
) ENGINE=InnoDB PARTITION BY RANGE(YEAR(ts))(
  PARTITION p25 VALUES LESS THAN(2026),
  PARTITION p26 VALUES LESS THAN(2027),
  PARTITION pmax VALUES LESS THAN MAXVALUE
);
