-- MySQL Partitioned Store 1097
CREATE DATABASE IF NOT EXISTS telemetry_1097;
USE telemetry_1097;
CREATE TABLE IF NOT EXISTS events_1097 (
  id BIGINT NOT NULL AUTO_INCREMENT, device_id INT NOT NULL,
  val INT NOT NULL, ts DATETIME NOT NULL,
  PRIMARY KEY(id,ts), INDEX idx_1097(device_id,ts)
) ENGINE=InnoDB PARTITION BY RANGE(YEAR(ts))(
  PARTITION p25 VALUES LESS THAN(2026),
  PARTITION p26 VALUES LESS THAN(2027),
  PARTITION pmax VALUES LESS THAN MAXVALUE
);
