-- MySQL Partitioned Store 6005
CREATE DATABASE IF NOT EXISTS telemetry_6005;
USE telemetry_6005;
CREATE TABLE IF NOT EXISTS events_6005 (
  id BIGINT NOT NULL AUTO_INCREMENT, device_id INT NOT NULL,
  val INT NOT NULL, ts DATETIME NOT NULL,
  PRIMARY KEY(id,ts), INDEX idx_6005(device_id,ts)
) ENGINE=InnoDB PARTITION BY RANGE(YEAR(ts))(
  PARTITION p25 VALUES LESS THAN(2026),
  PARTITION p26 VALUES LESS THAN(2027),
  PARTITION pmax VALUES LESS THAN MAXVALUE
);
