-- MySQL Partitioned Store 4137
CREATE DATABASE IF NOT EXISTS telemetry_4137;
USE telemetry_4137;
CREATE TABLE IF NOT EXISTS events_4137 (
  id BIGINT NOT NULL AUTO_INCREMENT, device_id INT NOT NULL,
  val INT NOT NULL, ts DATETIME NOT NULL,
  PRIMARY KEY(id,ts), INDEX idx_4137(device_id,ts)
) ENGINE=InnoDB PARTITION BY RANGE(YEAR(ts))(
  PARTITION p25 VALUES LESS THAN(2026),
  PARTITION p26 VALUES LESS THAN(2027),
  PARTITION pmax VALUES LESS THAN MAXVALUE
);
