-- MySQL Partitioned Store 2025
CREATE DATABASE IF NOT EXISTS telemetry_2025;
USE telemetry_2025;
CREATE TABLE IF NOT EXISTS events_2025 (
  id BIGINT NOT NULL AUTO_INCREMENT, device_id INT NOT NULL,
  val INT NOT NULL, ts DATETIME NOT NULL,
  PRIMARY KEY(id,ts), INDEX idx_2025(device_id,ts)
) ENGINE=InnoDB PARTITION BY RANGE(YEAR(ts))(
  PARTITION p25 VALUES LESS THAN(2026),
  PARTITION p26 VALUES LESS THAN(2027),
  PARTITION pmax VALUES LESS THAN MAXVALUE
);
